### ISSUE TITLE
borrar etiquetas

### ISSUE THREAD

**Issue by carbeltor3** [carbeltor3/practica_dwec_gestor_presupuesto#3]
@pedroprieto
tengo un problema con la funcion BorrarEtiquetasHandle, creo el handleEvent en cada uno de las etiquetas y se pintan en el html, pero no consigo borrar las etiquetas. Entrando en la depuracion, no llega a entrar nunca en dicha funcion y siempre termina entrando en la funcion EditarHandle.
no encuentro donde esta el fallo.
A ver si me pudieras echar una mano para poder terminar la practica.
con la funcion BorrarHandle, me pasa un poco lo mismo, pero en este caso si borra el gasto, pero tambien termina entrando en EditarHandle.
Gracias

**Comment by pedroprieto** [comment]
Creo que lo has solucionando, ¿verdad?

**Comment by carbeltor3** [comment]
era un problema de donde colocaba el manejador de eventos
