### ISSUE TITLE
funcion anyadirGasto Formulario

### ISSUE THREAD

**Issue by carbeltor3** [carbeltor3/practica_dwec_gestor_presupuesto#4]
@pedroprieto

**Comment by pedroprieto** [comment]
Buenas,

El fallo está aquí:
https://github.com/carbeltor3/practica_dwec_gestor_presupuesto/blob/08f3f5f57407ca82d980d3fa16ca79828ced803a/js/gestionPresupuestoWeb.js#L371

Estás controlando el evento `click` del botón. Tienes que controlar el evento `submit` del formulario. Por eso te funciona a ti pero falla el test: el test testea el evento `submit`, mientras que tú controlas el `click` del botón.

Un saludo!
